[tool.semantic_release]
branch = "main"
version_scheme = "semver"
version_source = "package"
version_variable = "package/__init__.py:__version__"
changelog_file = "CHANGELOG.md"
commit_parser = "conventional"
commit_author = "github-actions <actions@github.com>"
hvcs = "github"
upload_to_pypi = false
upload_to_repository = true

[tool.semantic_release.branches.main]
prerelease = false
