name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install python-semantic-release

      - name: Run Semantic Release (Versioning)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          semantic-release version

      - name: Commit and Push Version Updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add your_package/__init__.py CHANGELOG.md
          git commit -m "chore(release): update version and changelog [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run Semantic Release (Publishing)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          semantic-release publish
